openapi: 3.0.0
paths:
  /api/v1/reports/all:
    get:
      operationId: ReportsController_getAllReports
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            default: 1
          description: The page number for pagination.
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
            default: 20
          description: The number of items per page for pagination.
      responses:
        "200":
          description: ""
info:
  title: PerfAI Dashboard API
  description: PerfAI Dashboard API
  version: "1.0"
  contact: {}
tags:
  - name: API
    description: ""
servers: []
