openapi: 3.0.0
paths:
  /api/v1/perf/engine/test_SSRF_Endpoint/{project_id}:
    post:
      summary: Test SSRF Endpoint
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: Id of the project
        - in: query
          name: url_1
          required: true
          schema:
            type: string
          description: A required query parameter
        - in: query
          name: url_2
          required: true
          schema:
            type: string
          description: A required query parameter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url_1:
                  type: string
                url_2:
                  type: number
                create_date:
                  type: number
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /api/v1/perf/engine/simple_get:
    get:
      summary: Simple Get
      description: Returns a simple success status.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
  /api/v1/perf/engine/logout:
    post:
      summary: Logout
      description: Logs out the user and returns a success status.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
info:
  title: PerfAI Dashboard API
  description: PerfAI Dashboard API
  version: "1.0"
  contact: {}
tags:
  - name: API
    description: ""
servers: []
