openapi: 3.0.0
paths:
  /api/v1/reports/date-range:
    get:
      summary: Get reports in a date range
      security:
        - jwt: []
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date-time
          required: true
          description: The start date of the range
        - in: query
          name: to
          schema:
            type: string
            format: date-time
          required: true
          description: The end date of the range
      responses:
        '200':
          description: A list of reports within the specified date range
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: The report ID
                    org_id:
                      type: string
                      description: The organization ID
                    report_file:
                      type: string
                      description: The report file
                    created_on:
                      type: string
                      format: date-time
                      description: The creation date of the report
        '400':
          description: Invalid date range
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
info:
  title: PerfAI Dashboard API
  description: PerfAI Dashboard API
  version: "1.0"
  contact: {}
tags:
  - name: API
    description: ""
servers: []
